### ISSUE TITLE
Possible title

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2020-evostar-variable-attack-surface#2]
Which is related to #1, and by choosing it, we will settle on focus

*Generation of diverse and hardened server configuration using evolutionary algorithms*

*No free lunch for cyberattackers: optimizing server security and variability via evolutionary algorithms*

**Comment by erseco** [comment]
The first one or any of this:

_Use of evolutionary algorithms to hardening of servers based on the moving target defense technique._

_Optimizing server security using an evolutionary algorithm approach of the moving target defense technique._

_See No Evil, Hear No Evil: how to distract cyber-attackers using evolutionary algorithms_

**Comment by JJ** [comment]
> The first one or any of this:
> 
> _Use of evolutionary algorithms to hardening of servers based on the moving target defense technique._
> 

This one is good, as long as you change it to:

*Using evolutionary algorithms for server hardening via the moving target defense technique*

**Comment by JJ** [comment]
Close with commit :+1:
