### ISSUE TITLE
Include experimental data in the repository

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2020-evostar-variable-attack-surface#8]
We need 30 runs, and for every run
* Running time
* Best fitness
* Number of optimal individuals obtained in every run.

**Comment by erseco** [comment]
The results are listed following this pattern:

`results_<individual>_<crossover>_<mutation>_<n>.txt`
- individual: 16, 32, 64
- crossover: 1 or 2 points
- mutation: random value or increment of one
- n: 1 to 15

p.e. the file results_16_1_random_9.txt has 16 individuals, crossover in 1 point and a random value mutation and is the 9 experiment execution
